#define ACTION_DEBUG
#define BOOTMAGIC_ROW 4
#define BOOTMAGIC_COLUMN 0
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define CHORDAL_HOLD
#define PERMISSIVE_HOLD
#define TAPPING_TERM 250
#define TAPPING_TERM_PER_KEY
#define FLOW_TAP_TERM 100
#define QUICK_TAP_TERM 100

#define CHARYBDIS_MINIMUM_DEFAULT_DPI 900
#define CHARYBDIS_MINIMUM_SNIPING_DPI 400

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
// only required if not setting mouse layer elsewhere
#define AUTO_MOUSE_DEFAULT_LAYER 5

#define MASTER_RIGHT

#define LAYER_STATE_8BIT
#define NO_ACTION_ONESHOT
// #define NO_ACTION_MACRO
#define NO_MUSIC_MODE
