#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define CHORDAL_HOLD

#define PERMISSIVE_HOLD
#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY

#define CHARYBDIS_CONFIG_SYNC
#define CHARYBDIS_MINIMUM_DEFAULT_DPI 800

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
// only required if not setting mouse layer elsewhere
#define AUTO_MOUSE_DEFAULT_LAYER 5

#define MASTER_RIGHT

#define LAYER_STATE_8BIT
#define NO_ACTION_ONESHOT
#define NO_ACTION_MACRO
