#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CHARYBDIS_MINIMUM_DEFAULT_DPI 800
#define PERMISSIVE_HOLD
#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY

// #define MATRIX_COL_PINS { GP28, GP21, GP6, GP7, GP8 }
// #define MATRIX_ROW_PINS { GP26, GP5, GP4, GP9 }
// #define RP2040_FLASH_GD25Q64CS

#define CHARYBDIS_CONFIG_SYNC
#define CHARYBDIS_CONFIG_SYNC
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
// only required if not setting mouse layer elsewhere
#define AUTO_MOUSE_DEFAULT_LAYER 5
