AUTOCORRECT_ENABLE = yes
BOOTLOADER = rp2040
CAPS_WORD_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes

BOOTMAGIC_ENABLE = no
COMBO_ENABLE = no
EXTRAKEY_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no

SRC += features/achordion.c
