AUTOCORRECT_ENABLE = yes
BOOTLOADER = rp2040
CAPS_WORD_ENABLE = yes
#COMBO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
REPEAT_KEY_ENABLE = yes

COMMAND_ENABLE = no
CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
SPACE_CADET_ENABLE = no
UNICODE_ENABLE = no

KEYCODE_STRING_ENABLE = yes
